### ISSUE TITLE
Question reguarding the use of sqrt in Grit attention

### ISSUE THREAD

**Issue by charlesxu90** [LiamMa/GRIT#1]
Dear @LiamMa,

Thanks very much for this nice work. I'm trying to reproduce the expriments. However, when I ran the code, it popped up an error during backpropgation as follows. This might because I reimplemented the trainers.

```python
File "~/Desktop/Pep_pred/ref_works/1.graph/gps_demos/grit/model/grit_layer.py", line 212, in forward
    h_attn_out, e_attn_out = self.attention(batch)
  File "~/miniconda3/envs/cp2pred-env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/Desktop/Pep_pred/ref_works/1.graph/gps_demos/grit/model/grit_layer.py", line 156, in forward
    edge_w = torch.sqrt(torch.relu(edge_w)) - torch.sqrt(torch.relu(-edge_w))
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
...

File "~/miniconda3/envs/cp2pred-env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'SqrtBackward0' returned nan values in its 0th output.
```
The error comes from this line of code.
```python
score= torch.sqrt(torch.relu(score)) - torch.sqrt(torch.relu(-score))
```
But basically, this line is just trying to down-scale the value of score by calling `sqrt()`. Is it necessary to use this function? Any reason for add it in `Grit layer`? Is it okay if I remove it?

My reimplementation of 'Grit' can be found here. https://github.com/charlesxu90/gps_demo/tree/main/grit

**Comment by LiamMa** [comment]
Hello @charlesxu90, we appreciate your interest in our work.

The signed-square-root is added to enhance the training stability with batch normalization.  If you're not encountering training instability, you can opt to omit this step without concern.

Concerning the issue, a potential explanation could be that your current pytorch version cannot handle `torch.sqrt()` with zero-value elements in Tensors, as elaborated in this [discussion](https://discuss.pytorch.org/t/runtimeerror-function-sqrtbackward-returned-nan-values-in-its-0th-output/48702).
In the version applied in GRIT (1.12.1 or 1.13.1), it is supported and we haven't come across this issue. 
As an alternative approach, you might introduce a small epsilon value to zero elements, as suggested in [this reply](https://discuss.pytorch.org/t/runtimeerror-function-sqrtbackward-returned-nan-values-in-its-0th-output/48702/4).

**Comment by charlesxu90** [comment]
Thanks for the elaboration. The version I'm writing runs smoothly without `sqrt()`. However, if added, the `loss.backward()` will not work, even if I added the epsilon value in `sqrt()`.

I'm using pytorch '2.0.1+cu118' with amp for mixed precision computing. I'm not sure if it is the problem with this. 

Anyway, thanks for your response.

**Comment by charlesxu90** [comment]
BTW, after removing the precision can achieve up to 79.4 in 4 epochs on Peptides-func
[Leaderboard](https://paperswithcode.com/sota/graph-classification-on-peptides-func#) benchmark. Seems to be very promising.
![image](https://github.com/LiamMa/GRIT/assets/5413227/7a5778f8-2356-477e-9921-e084d2f40c3e)

**Comment by charlesxu90** [comment]
The nan loss would be a problem after 10 epochs. Seems the best performance has already achieved within 10 epochs.

I'll remove this in my code. Thanks.

**Comment by charlesxu90** [comment]
I tested it on a new dataset with only 7000 samples. The model overfit in just one epoch.
```shell
epoch 1 iter 33: train loss 0.92820.:  18%|█████████████████████████████████████████████████▍                                                                                                                                                                                                                              | 34/187 [00:07<00:19,  7.92it/s]2023-08-29 10:17:40.864 | INFO     | grit.task_trainer:train_epoch:99 - Anomaly loss detected at epoch 1 iter 34: train loss 41.92969.
epoch 1 iter 33: train loss 0.92820.:  18%|█████████████████████████████████████████████████▍                                                                                                                                                                                                                              | 34/187 [00:07<00:32,  4.67it/s]
2023-08-29 10:17:42.366 | INFO     | grit.task_trainer:eval_epoch:136 - val epoch: 1, loss: 205.8712
2023-08-29 10:17:42.377 | INFO     | grit.task_trainer:eval_epoch:144 - val epoch: 1, spearman: 0.299, pearson: 0.309, mse: 209.536, mae: 11.101
2023-08-29 10:17:44.069 | INFO     | grit.task_trainer:eval_epoch:136 - test epoch: 1, loss: 280.0945
2023-08-29 10:17:44.077 | INFO     | grit.task_trainer:eval_epoch:144 - test epoch: 1, spearman: 0.280, pearson: 0.369, mse: 287.695, mae: 13.144
epoch 2 iter 26: train loss 0.30369.:  14%|███████████████████████████████████████▎                                                                                                                                                                                                                                        | 27/187 [00:04<00:25,  6.33it/s]2023-08-29 10:17:48.773 | INFO     | grit.task_trainer:train_epoch:99 - Anomaly loss detected at epoch 2 iter 27: train loss 434.75879.
epoch 2 iter 26: train loss 0.30369.:  14%|███████████████████████████████████████▎                                                                                                                                                                                                                                        | 27/187 [00:04<00:25,  6.27it/s]
2023-08-29 10:17:50.356 | INFO     | grit.task_trainer:eval_epoch:136 - val epoch: 2, loss: 2278.5161
2023-08-29 10:17:50.360 | INFO     | grit.task_trainer:eval_epoch:144 - val epoch: 2, spearman: 0.173, pearson: 0.198, mse: 2318.165, mae: 42.775
2023-08-29 10:17:52.006 | INFO     | grit.task_trainer:eval_epoch:136 - test epoch: 2, loss: 3006.1284
2023-08-29 10:17:52.014 | INFO     | grit.task_trainer:eval_epoch:144 - test epoch: 2, spearman: 0.269, pearson: 0.315, mse: 3070.924, mae: 49.825
epoch 3 iter 26: train loss 0.45482.:  14%|███████████████████████████████████████▎                                                              
```
I suppose this model is better suited to be train on a very large dataset.

**Comment by LiamMa** [comment]
> I'm using pytorch '2.0.1+cu118' with amp for mixed precision computing. I'm not sure if it is the problem with this.

Hi @charlesxu90, we haven't tried mixed-precision computing before. This might be the reason. Thank you for putting it on the table.

> I suppose this model is better suited to be train on a very large dataset.

It is not only related to the size of the dataset but also related to how challenging the task is. If the dataset/task is less demanding on expressive power, considering a simpler architecture and/or fewer parameters might be a good choice.
